Construct a matrix as a numpy array

1      0.2     0.5
0.2    1       0.8
0.5    0.8     1

In [4]:
#matrix 

import numpy as np

mymatrix = np.array([[1, 0.2 , 0.5 ],
                     [0.2 , 1 , 0.8], 
                     [0.5 , 0.8 , 1]])

print(mymatrix)


[[1.  0.2 0.5]
 [0.2 1.  0.8]
 [0.5 0.8 1. ]]


In [3]:
#Inversion of matrix

print(np.linalg.inv(mymatrix))


[[ 1.56521739  0.86956522 -1.47826087]
 [ 0.86956522  3.26086957 -3.04347826]
 [-1.47826087 -3.04347826  4.17391304]]


In [6]:
#Determinant of the matrix

determinant = np.linalg.det(mymatrix)

print(determinant)


0.2299999999999999


In [9]:
#Decompose the matrix

decomposition = np.linalg.qr(mymatrix)

print(decomposition)


QRResult(Q=array([[-0.88045091,  0.38615039, -0.27512557],
       [-0.17609018, -0.80507368, -0.566435  ],
       [-0.44022545, -0.4502713 ,  0.77682515]]), R=array([[-1.13578167, -0.70436073, -1.02132305],
       [ 0.        , -1.08806065, -0.90125505],
       [ 0.        ,  0.        ,  0.18611436]]))


In [10]:
#Transfrom the matrix

transformation = mymatrix.transpose() 

print(transformation)



[[1.  0.2 0.5]
 [0.2 1.  0.8]
 [0.5 0.8 1. ]]
